Tugas 2
tidak mengerjakan tidak boleh masuk kelas

In [ ]:
## Aljabar Matrix

- Berikan penjelasan tentang apa itu Matrix

- Operasi Matrix

- Penjumlahan perkalian, pengurangan, transpose matrix

- Buat program untuk mengalikan matrix A dan B

In [5]:
import numpy as np

In [9]:
#Contoh Matrix
A = np.array([[8,9,3],[1,2,5],[2,1,1]])
B = np.array([[2,6,4],[1,2,3],[2,5,5]])
C = np.array([[9,2],[2,5],[4,0]])
D = np.array([[1,8,6],[0,5,3],[1,9,2]])

print("A= \n", A)
print("B= \n", B)
print("C= \n", C)
print("D= \n", D)

A= 
 [[8 9 3]
 [1 2 5]
 [2 1 1]]
B= 
 [[2 6 4]
 [1 2 3]
 [2 5 5]]
C= 
 [[9 2]
 [2 5]
 [4 0]]
D= 
 [[1 8 6]
 [0 5 3]
 [1 9 2]]


In [13]:
A = np.array([[2,3,4],[5,6,7],[8,9,1]])
print("A = \n", A)
print()

B = np.array([[5,2,4],[3,7,9],[2,2,4]])
print("B = \n", B)
print()

#operasi matrix
print("E = \n", A+B)
print("F = \n", 2*A)
print("G = \n", A@C)

A = 
 [[2 3 4]
 [5 6 7]
 [8 9 1]]

B = 
 [[5 2 4]
 [3 7 9]
 [2 2 4]]

E = 
 [[ 7  5  8]
 [ 8 13 16]
 [10 11  5]]
F = 
 [[ 4  6  8]
 [10 12 14]
 [16 18  2]]
G = 
 [[40 19]
 [85 40]
 [94 61]]


In [18]:
print(A@(B@C))
print((A@B)@C)

print("-"*40)

print(7*(A@B))
print((7*A)@B)
print(A@(7*B))


[[ 513  219]
 [1053  444]
 [1251  543]]
[[ 513  219]
 [1053  444]
 [1251  543]]
----------------------------------------
[[189 231 357]
 [399 462 714]
 [483 567 819]]
[[189 231 357]
 [399 462 714]
 [483 567 819]]
[[189 231 357]
 [399 462 714]
 [483 567 819]]


In [25]:
C = np.array([[9,2],[2,5],[4,0]])
print("C = \n", C)
C_T = C.transpose()
print(C_T)
print("-"*30)
print(C_T@C)
print("-"*30)
print(C@C_T)


C = 
 [[9 2]
 [2 5]
 [4 0]]
[[9 2 4]
 [2 5 0]]
------------------------------
[[101  28]
 [ 28  29]]
------------------------------
[[85 28 36]
 [28 29  8]
 [36  8 16]]
