# **Tugas 2**

## Berikan pengertian apa itu matrix

Buatlah Matrix A(3x3),B(2x3),C(3x2)

-Operasi matrix

*   Penjumlahan
*   Perkalian
*   Pengurangan
*   Tranpose matrix

Buat program untuk mengkalikan Matrix A dengan Matrix B tidak menggunakan @



## Pengertian Matrix
Matrix adalah susunan bilangan real atau bilangan kompleks (atau elemen-elemen) yang disusun dalam baris dan kolom sehingga membentuk jajaran persegi panjang.

Matrix terdiri dari beberapa jenis sebagai berikut :

*  Matrix persegi
*  Matrix kolom
*  Matrix baris
*  Matrix Transpose

Operasi Matrix

Operasi Matrix adalah operasi yang dilakukan terhadap sebuah satu atau lebih matrix .Operasi matrix pada dasarnya meliputi : penjumlahan, pengurangan, perkalian.

1.  Penjumlahan matrix <br>
penjumlahan matrix adalah penjumlahan yang dilakukan terhadap dua buah matrix dengan komponen=komponennya yang seletak. Matrix ini dapat dijumlahkan jika jumlah baris dan kolomnya sama dan juga hasil dari penjumlahan ini juga akan memiliki ordo yang sama.

In [2]:
import numpy as np

In [3]:
# Contoh Matrix

A = np.array([[1,4,8],[2,-2,5],[7,3,1]]) # matrix 3x3
B = np.array([[2,6,3],[3,4,4],[2,-1,6]]) # matrix 3x3
C = np.array([[3,5],[-2,3],[4,3]]) # matrix 3x2
D = np.array([[2,5,8],[2,-4,5],[-3,5,2]]) # matrix 3x3
E = (A+B)
F = 2*(A)
G = A @ C

In [4]:
print(f"Matrix A 3x3: \n{A}")
print(f" Matrix B 3x3: \n{B}")
print(f"Matrix C 3x2: \n{C}")
print(f"Matrix D 3x3: \n{D}")

Matrix A 3x3: 
[[ 1  4  8]
 [ 2 -2  5]
 [ 7  3  1]]
 Matrix B 3x3: 
[[ 2  6  3]
 [ 3  4  4]
 [ 2 -1  6]]
Matrix C 3x2: 
[[ 3  5]
 [-2  3]
 [ 4  3]]
Matrix D 3x3: 
[[ 2  5  8]
 [ 2 -4  5]
 [-3  5  2]]


In [5]:
# Matrix A+B
E = (A+B)
print(f"Matrix E =\n{E}")

Matrix E =
[[ 3 10 11]
 [ 5  2  9]
 [ 9  2  7]]


2.  Operasi Pengurangan Matrix


In [6]:
# Matrix A - B
G  = A - B
print(f"Matrix G =\n{G}")

Matrix G =
[[-1 -2  5]
 [-1 -6  1]
 [ 5  4 -5]]


### Operasi Perkalian Matrix

In [7]:
# Matrix A x C
H = A @ C
print(f"Matrix H =\n{H}")
print(f"Ukuran Matrix = {H.shape}")

Matrix H =
[[27 41]
 [30 19]
 [19 47]]
Ukuran Matrix = (3, 2)


### Tranpose Matrix

Anggap Baris = m, Kolom = n

C = A_trans @ A

(n x m) @ (m x n) = n * n

contoh: [2 x 3] @ [3 x 2] = [2 x 2]

C = A @ A_trans

(m x n) @ (n x m) = m x m

contoh: [3 x 2] @ [2 x 3] = [3 x 3]

In [8]:
# Contoh dengan Martrix 3x3

A_tran = A.transpose()
print('Matrik A sebelum di transpose=\n', A)
print()
print('Matrik A setelah di transpose=\n',A_tran)
print('Ordo A_transpose adalah',A_tran.shape)
Z = A_tran @ A
print()
print('Z = A_transpose x A =\n',Z)
print('Ordo Z adalah',Z.shape)
print()
P=A @ A_tran
print('P = A_transpose x A =\n',P)
print('Ordo P adalah',P.shape)

Matrik A sebelum di transpose=
 [[ 1  4  8]
 [ 2 -2  5]
 [ 7  3  1]]

Matrik A setelah di transpose=
 [[ 1  2  7]
 [ 4 -2  3]
 [ 8  5  1]]
Ordo A_transpose adalah (3, 3)

Z = A_transpose x A =
 [[54 21 25]
 [21 29 25]
 [25 25 90]]
Ordo Z adalah (3, 3)

P = A_transpose x A =
 [[81 34 27]
 [34 33 13]
 [27 13 59]]
Ordo P adalah (3, 3)


### Program untuk mengkalikan Matrix A dengan Matrix B Secara Manual tidak menggunakan '@'


In [9]:
Matrix_1 = [[2,4,9],
            [6,-1,3],
            [7,3,4]]

Matrix_2 = [[5,3,2],
            [8,3,5],
            [5,-2,5]]
Result = []

print(f" Matrix_1 = {Matrix_1}")
print()
print(f" Matrix_2 = {Matrix_2}")

def multiply_matrix(matrix1,matrix2):
  result = [[0,0,0],[0,0,0],[0,0,0]] # Menginisialisasikan dulu matrix dengan semua value 0

  for i in range(len(Matrix_1)):
    for j in range(len(Matrix_2[0])):
      for k in range(len(Matrix_2)):
        result[i][j] += Matrix_1[i][k] * Matrix_2[k][j]
  return result

hasil = multiply_matrix(Matrix_1,Matrix_2)
print()
print(f"Hasil perkalian Matrix_1 dan Matrix 2 = {hasil}")
print()
print(f"Pembuktian untuk Matrix A @ B =\n{A @ B}")

 Matrix_1 = [[2, 4, 9], [6, -1, 3], [7, 3, 4]]

 Matrix_2 = [[5, 3, 2], [8, 3, 5], [5, -2, 5]]

Hasil perkalian Matrix_1 dan Matrix 2 = [[87, 0, 69], [37, 9, 22], [79, 22, 49]]

Pembuktian untuk Matrix A @ B =
[[30 14 67]
 [ 8 -1 28]
 [25 53 39]]
